### ISSUE TITLE
Use deterministic channelId

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-ethereum#2]
https://github.com/hoprnet/hopr-ethereum/blob/3e8a6cc77b01fef532c09beb82fb051dacb58905/contracts/HoprChannels.sol#L107

Two-dimensional maps waste far more space than one-dimensional. Consider using a deterministic Id, e.g. 
```
channel_id = keccak256(abi.encodePacked(party_a, party_b))
```
where `addr(party_a) < addr(party_b)`

**Comment by nionis** [comment]
@robertkiel thx for the feedback, HoprChannels.sol will be reworked to support bidirectional payments similar to polkadot's smart contracts.
