### ISSUE TITLE
Comment does not match code

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-ethereum#25]
The [comment](https://github.com/hoprnet/hopr-ethereum/blob/dfa14c4733dc2bd42c427f6e8d1c24ee84cdec90/contracts/HoprChannels.sol#L386) reads `if operator is self` but the code says `operator != address(this)` - I guess the comment is wrong?

**Comment by nionis** [comment]
`if operator is self (fundWithSignature), don't call fundChannel` taken full context it makes more sense but I will still update it something more intuitive

**Comment by nionis** [comment]
https://github.com/hoprnet/hopr-ethereum/blob/6eeffdba7948b44b8fe7ab072b7930f31ed74384/contracts/HoprChannels.sol#L392
