### ISSUE TITLE
add comment for state counter

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-ethereum#26]
We should explain non-obvious concepts in the code with comments. E.g. when [increasing the state counter upon funding a new channel](https://github.com/hoprnet/hopr-ethereum/blob/dfa14c4733dc2bd42c427f6e8d1c24ee84cdec90/contracts/HoprChannels.sol#L140) should be explained by e.g. `Increase state counter so that we can re-use the same channel after it has been closed. Thus the state counter indicates the recycling generation and ensures that both parties are using the correct generation.`

**Comment by nionis** [comment]
when closing: https://github.com/hoprnet/hopr-ethereum/blob/6eeffdba7948b44b8fe7ab072b7930f31ed74384/contracts/HoprChannels.sol#L367-L368

rest: https://github.com/hoprnet/hopr-ethereum/blob/6eeffdba7948b44b8fe7ab072b7930f31ed74384/contracts/HoprChannels.sol#L328

what do you think?

**Comment by jjperezaguinaga** [comment]
@SCBuergel this one is completed, please take a look and check it out.
