### ISSUE TITLE
Use verification / simulate state change / state change scheme

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-ethereum#5]
https://github.com/hoprnet/hopr-ethereum/blob/3e8a6cc77b01fef532c09beb82fb051dacb58905/contracts/HoprChannels.sol#L169

It is much safer to do all verification _before_ doing any state change. A workflow could look like this

```
// verification
require( sth != 0 ) // some checks
// simulate state change
a + b != uint256(0) // does not cause an overflow
// perform state change
sum = a + b // save to memory
```

**Comment by nionis** [comment]
@robertkiel @SCBuergel 

would you rather use [method A](https://github.com/hoprnet/hopr-ethereum/blob/feat/bidirectional-channels/contracts/HoprChannels.sol#L211) or [method B](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/SafeERC20.sol).

I assume latter uses more gas? I am not sure about that.
