### ISSUE TITLE
overwrite deleted entry with 0

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-ethereum#6]
https://github.com/hoprnet/hopr-ethereum/blob/3e8a6cc77b01fef532c09beb82fb051dacb58905/contracts/HoprChannels.sol#L303

You may consider using

```
delete channels[0]
```

instead of setting each entry explicitly to 0.

**Comment by nionis** [comment]
@SCBuergel I remember you preferred I use `0` instead of delete, would you like to provide feedback on this?

**Comment by SCBuergel** [comment]
@nionis don't recall what that was about, sorry. But here I'd agree with Robert's suggestion.
