### ISSUE TITLE
failure to verify smart contracts on solidity ^0.6.0

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-ethereum#67]
tracking this issue https://github.com/rkalis/truffle-plugin-verify/issues/30

**Comment by jjperezaguinaga** [comment]
@nionis Moving this back to Backlog for our sprint planning, and then we can see if we move this to the next sprint.

**Comment by nionis** [comment]
turns out this issue was due to the etherscan API and not our solidity version
