### ISSUE TITLE
update addresses on migration

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-ethereum#68]

**Comment by jjperezaguinaga** [comment]
@nionis are we following up on this one or is it a stale thread?

**Comment by jjperezaguinaga** [comment]
@nionis It has become increasingly important to achieve this as we restore the token to be part of the protocol. Have you thought about something? I'm in favour of writing the addresses during the migration as we discussed at some point.

**Comment by nionis** [comment]
@jjperezaguinaga I haven't given this any thought yet, as you mentioned, I think we can extract the migrated addresses though truffle or by looking in the truffle artifacts, and afterwards we include them in the package.
