### ISSUE TITLE
This was only necessary for Substrate 

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-ethereum#8]
https://github.com/hoprnet/hopr-ethereum/blob/3e8a6cc77b01fef532c09beb82fb051dacb58905/contracts/HoprChannels.sol#L137

In Substrate, `publickey` and `accountId` might not be the same. Therefore this line of code was necessary

**Comment by nionis** [comment]
@robertkiel The reason I use this variable is for readability only
